I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 61, in script
    python:
  File "game/script.rpy", line 62, in <module>
    items = game.current_location.loc_content["Items"]
AttributeError: 'Game' object has no attribute 'current_location'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 61, in script
    python:
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Ren'Py\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 62, in <module>
    items = game.current_location.loc_content["Items"]
AttributeError: 'Game' object has no attribute 'current_location'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
School of The Damned 1.0
Tue Aug 13 14:41:33 2024
